services:
  - type: web
    name: webapps
    env: python
    pythonVersion: "3.12.18"
    buildCommand: "pip install --upgrade pip setuptools wheel && pip install -r requirements.txt"
    startCommand: "gunicorn app:app --bind 0.0.0.0:$PORT --workers 2"
